web:
  build: ./docker/ubuntu
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./app:/var/www/html
  working_dir: /var/www/html
  links:
    - mysql
    #- psql

mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=drupal
    - MYSQL_DATABASE=lichida3_et3
    - MYSQL_USER=lichida3_klopp
    - MYSQL_PASSWORD=Xa4C1Vufeg8TNyZ
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes:
    - ./db:/app
  ports:
    - "3306:3306"

#psql:
#  image: kiasaki/alpine-postgres
#  environment:
#    - POSTGRES_PASSWORD=drupal
#    - POSTGRES_USER=drupal
#    - POSTGRES_DB=drupal
#  # ports:
#  #   - "5432:5432"
